"use client";

import React from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Code, Book, Terminal } from "lucide-react";

const docSections = [
  {
    id: "getting-started",
    title: "Getting Started",
    icon: <Book />,
    description: "Learn how to set up your environment and start using the emb.web AI tools to build your first project.",
    details: (
      <div className="prose dark:prose-invert max-w-none">
        <p>Welcome to emb.web! This guide will walk you through the core features available in your dashboard.</p>
        <h3>The Dashboard</h3>
        <p>The dashboard is your central hub for creating and managing your web projects. It's organized into several tabs:</p>
        <ul>
          <li><strong>Code Forge:</strong> This is where the magic happens. Use natural language to prompt the AI and generate React components in seconds.</li>
          <li><strong>My Snippets:</strong> Every piece of code you save from the Code Forge is stored here for easy access, editing, and reuse.</li>
          <li><strong>Design Advisor:</strong> Customize the look and feel of the entire application in real-time. Experiment with colors or let the AI suggest a palette for you.</li>
          <li><strong>Blog Admin:</strong> A full-featured content management system for your blog. Create, edit, and delete posts with a simple interface.</li>
        </ul>
        <p>We encourage you to explore each tab to see the full power of the platform.</p>
      </div>
    )
  },
  {
    id: "code-snippets",
    title: "Code Snippets & Customization",
    icon: <Code />,
    description: "Explore a library of code snippet examples generated by our AI. Learn how to customize them to fit your specific needs.",
    details: (
        <div className="prose dark:prose-invert max-w-none">
            <p>The Code Forge and My Snippets tabs work together to provide a seamless workflow for generating and managing code.</p>
            <h3>Generating Code</h3>
            <ol>
                <li>Navigate to the <strong>Code Forge</strong> tab on your dashboard.</li>
                <li>In the text area, type a clear and descriptive prompt for the component you want to build (e.g., "a pricing card with three tiers").</li>
                <li>Click the "Generate Code" button. The AI will process your request and display the generated React component in the code viewer below.</li>
            </ol>
            <h3>Saving and Managing Snippets</h3>
            <ul>
                <li>Once code is generated, a "Save Snippet" button will appear. Click it to save the code and its prompt to your personal library.</li>
                <li>Go to the <strong>My Snippets</strong> tab to see all your saved snippets.</li>
                <li>From here, you can <strong>Edit</strong> the prompt and code, <strong>Copy</strong> the code to your clipboard, or <strong>Delete</strong> the snippet permanently.</li>
            </ul>
        </div>
    )
  },
  {
    id: "api-reference",
    title: "API Reference",
    icon: <Terminal />,
    description: "For advanced users, our API reference provides detailed information on how to embed our AI builder into your own applications.",
    details: (
        <div className="flex items-center justify-center h-32">
            <p className="text-muted-foreground">[Content for API Reference coming soon]</p>
        </div>
    )
  }
];

export default function DocsPage() {
  return (
    <div className="container mx-auto max-w-screen-xl px-4 py-16 md:px-6 md:py-24">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="text-center mb-12"
      >
        <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
          Documentation
        </h1>
        <p className="mt-4 max-w-[700px] mx-auto text-muted-foreground md:text-xl">
          Your guide to building faster with emb.web.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-[250px_1fr] gap-12">
        <aside className="hidden md:block">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="sticky top-24"
          >
            <h3 className="text-lg font-semibold mb-4">On this page</h3>
            <ul className="space-y-2">
              {docSections.map(section => (
                <li key={section.id}>
                  <a href={`#${section.id}`} className="text-muted-foreground hover:text-primary transition-colors">
                    {section.title}
                  </a>
                </li>
              ))}
            </ul>
          </motion.div>
        </aside>

        <main>
          <motion.div
            initial="hidden"
            animate="visible"
            variants={{
                hidden: { opacity: 0 },
                visible: { opacity: 1, transition: { staggerChildren: 0.2 } }
            }}
            className="space-y-12"
          >
            {docSections.map(section => (
              <motion.section
                key={section.id}
                id={section.id}
                variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0 } }}
              >
                <Card>
                  <CardHeader className="flex flex-row items-center gap-4">
                    {React.cloneElement(section.icon, { className: "h-6 w-6 text-primary" })}
                    <CardTitle className="text-2xl">{section.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground mb-6">{section.description}</p>
                    <div className="border-t pt-6">
                        {section.details}
                    </div>
                  </CardContent>
                </Card>
              </motion.section>
            ))}
          </motion.div>
        </main>
      </div>
    </div>
  );
}