"use client";

import React from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Code, Book, Terminal } from "lucide-react";

const docSections = [
  {
    id: "getting-started",
    title: "Getting Started",
    icon: <Book />,
    content: "Learn how to set up your environment and start using the emb.web AI tools to build your first project. We'll guide you through the initial steps to get you up and running in minutes."
  },
  {
    id: "code-snippets",
    title: "Code Snippets & Customization",
    icon: <Code />,
    content: "Explore a library of code snippet examples generated by our AI. Learn how to customize them to fit your specific needs, from changing styles to modifying functionality."
  },
  {
    id: "api-reference",
    title: "API Reference",
    icon: <Terminal />,
    content: "For advanced users, our API reference provides detailed information on how to embed our AI builder into your own applications and workflows. (Coming Soon)"
  }
];

export default function DocsPage() {
  return (
    <div className="container mx-auto max-w-screen-xl px-4 py-16 md:px-6 md:py-24">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="text-center mb-12"
      >
        <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
          Documentation
        </h1>
        <p className="mt-4 max-w-[700px] mx-auto text-muted-foreground md:text-xl">
          Your guide to building faster with emb.web.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-[250px_1fr] gap-12">
        <aside className="hidden md:block">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="sticky top-24"
          >
            <h3 className="text-lg font-semibold mb-4">On this page</h3>
            <ul className="space-y-2">
              {docSections.map(section => (
                <li key={section.id}>
                  <a href={`#${section.id}`} className="text-muted-foreground hover:text-primary transition-colors">
                    {section.title}
                  </a>
                </li>
              ))}
            </ul>
          </motion.div>
        </aside>

        <main>
          <motion.div
            initial="hidden"
            animate="visible"
            variants={{
                hidden: { opacity: 0 },
                visible: { opacity: 1, transition: { staggerChildren: 0.2 } }
            }}
            className="space-y-12"
          >
            {docSections.map(section => (
              <motion.section
                key={section.id}
                id={section.id}
                variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0 } }}
              >
                <Card>
                  <CardHeader className="flex flex-row items-center gap-4">
                    {React.cloneElement(section.icon, { className: "h-6 w-6 text-primary" })}
                    <CardTitle className="text-2xl">{section.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{section.content}</p>
                    <div className="mt-6 border rounded-lg p-8 bg-background/50 flex items-center justify-center">
                      <p className="text-sm text-muted-foreground">[Content for {section.title} coming soon]</p>
                    </div>
                  </CardContent>
                </Card>
              </motion.section>
            ))}
          </motion.div>
        </main>
      </div>
    </div>
  );
}