// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hulzlozbtojpzqwpdvtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bHpsb3pidG9qcHpxd3BkdnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODExMzUsImV4cCI6MjA2NzU1NzEzNX0.wrjL9gKD2-DvE9_yqE2_0m7o6or1Y2P2q6T-G6qwiow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);